sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # git commit SHA and set as env var
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #download gcloud sdk then install locally on instance assigned by travis CI
  - source $HOME/google-cloud-sdk/path.bash.inc # modify shell to set up gcloud
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-404515
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password
  - docker build -t spencercarlson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true spencercarlson/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
