apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector: # which pods cluster ip service is managing access to
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
